config/routes.rb
Rails.application.routes.draw do
  get 'sample/index'
  post 'sample/index'
  root 'sample#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sample_controller.rb
class SampleController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sample_helper.rb
module SampleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RilsSampleVuejs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sample/index.html.erb
<h1>VueJS+Ajax Sample</h1>

<hr>

バインディング１<br>
-ボタン押下でテキスト更新-<br><br>

<div id="app">
  <p>{{ message }}</p>
  <button v-on:click="refreshMessage">現在時刻(VueJS)</button>
</div>

<%= button_to "現在時刻(Ajax)" , sample_index_path ,remote: true %>

<hr>

バインディング２<br>
-テキストボックスの値変更でテキスト更新-<br><br>

<div id="app2">
  <p>テキスト：{{ txt }}</p>
  <p>文字数　：{{ len }}</p>
  <input v-model="txt">
</div>


<script src="https://unpkg.com/vue"></script>

<script>
    var app = new Vue({
        el: '#app',
        data: {
            message: 'Hello Vue!'
        },
        methods: {
            refreshMessage: function () {
                this.message = new Date();
            }
        }
    })

    var app2 = new Vue({
        el: '#app2',
        data: {
            txt: 'Hello Vue!',
            len: '0'
        },
        created: function () {
            this.len = this.txt.length;
        }
    })


    // リスナー
    // https://jp.vuejs.org/v2/guide/instance.html
    // $watch はインスタンスメソッドです
    app2.$watch('txt', function () {
        // このコールバックは `app6.message` の値が変わる時に呼ばれます
        //console.log(app2.txt);
        //console.log(app2.len);
        app2.len = app2.txt.length;
    })
</script>

app/views/sample/index.js.erb
app.message = new Date();